import * as esbuild from 'esbuild'
import { readFileSync, existsSync, mkdirSync, unlinkSync } from 'node:fs'

const pkg = JSON.parse(readFileSync('package.json', 'utf-8'))

// Only keep Node.js built-ins external — everything else gets bundled inline
const external = ['node:*']

// Ensure api/ dir exists
if (!existsSync('api')) {
  mkdirSync('api')
}

await esbuild.build({
  entryPoints: ['api/index.ts'],
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'cjs',
  outfile: 'api/index.js',
  external,
  resolveExtensions: ['.ts', '.tsx', '.js', '.json'],
  banner: {
    js: `// Auto-generated by build-vercel.mjs\n// ${pkg.name}@${pkg.version} — built for Vercel`,
  },
})

// Remove the .ts file so Vercel only sees the compiled .js
unlinkSync('api/index.ts')

console.log('✅ api/index.js built successfully, api/index.ts removed')
