import * as esbuild from 'esbuild'
import { readFileSync, existsSync, mkdirSync, unlinkSync, writeFileSync } from 'node:fs'

const pkg = JSON.parse(readFileSync('package.json', 'utf-8'))

const external = ['node:*']

if (!existsSync('api')) {
  mkdirSync('api')
}

// Build as ESM — avoids the CJS module.exports ordering issue
await esbuild.build({
  entryPoints: ['api/index.ts'],
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  outfile: 'api/index.mjs',
  external,
  resolveExtensions: ['.ts', '.tsx', '.js', '.json'],
  banner: {
    js: `// Auto-generated by build-vercel.mjs\n// ${pkg.name}@${pkg.version} — built for Vercel`,
  },
})

// Remove .ts file so Vercel doesn't re-compile it
unlinkSync('api/index.ts')

console.log('✅ api/index.mjs built successfully (ESM format)')
